package lexico;

// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: /home/andaryus7/Documentos/Compiladores 1/proyecto01/lexicoJava.flex

/*primer seccion codigo de usuario*/
//package ;

import java.util.ArrayList;

import java_cup.runtime.*;
import objetosAnalisis.Token;
import objetosAnalisis.errorE;
import sintactico.sym;
import tablaSimbolo.TablaSimbolo;




// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LexicoJava implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int CADE = 2;
  public static final int COMENTMULTILINEA = 4;
  public static final int COMENTLINEA = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\3\1\22\0\1\1\1\3\1\4"+
    "\3\0\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\12\17\1\20\1\21\1\22\1\23"+
    "\1\24\2\0\22\25\1\26\7\25\4\0\1\27\1\0"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\25\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\25\1\47\1\50\1\51\1\52\1\53\1\54\3\25"+
    "\1\55\1\56\1\57\7\0\1\1\32\0\1\1\120\0"+
    "\1\25\u018e\0\1\1\177\0\13\1\35\0\2\1\5\0"+
    "\1\1\57\0\1\1\240\0\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\2\23\1\1\14\23\1\24"+
    "\1\2\1\25\1\26\1\27\1\30\2\31\1\32\1\33"+
    "\1\34\1\0\1\35\1\36\1\0\1\37\1\40\1\41"+
    "\1\0\7\23\1\42\4\23\1\43\11\23\1\44\1\45"+
    "\1\46\13\23\1\47\1\23\1\50\1\51\12\23\1\52"+
    "\1\53\3\23\1\54\10\23\1\55\3\23\1\56\1\57"+
    "\2\23\1\60\1\61\6\23\1\62\1\63\2\23\1\64"+
    "\1\65\2\23\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\2\23\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\300\0\360\0\300"+
    "\0\u0120\0\u0150\0\300\0\300\0\300\0\300\0\300\0\300"+
    "\0\300\0\u0180\0\u01b0\0\300\0\300\0\u01e0\0\u0210\0\u0240"+
    "\0\u0270\0\u02a0\0\u0270\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390"+
    "\0\u03c0\0\u03f0\0\u0420\0\u0450\0\u0480\0\u04b0\0\u04e0\0\300"+
    "\0\u0510\0\300\0\300\0\300\0\300\0\300\0\u0540\0\300"+
    "\0\300\0\300\0\u0570\0\300\0\300\0\u05a0\0\300\0\300"+
    "\0\300\0\u0270\0\u05d0\0\u0600\0\u0630\0\u0660\0\u0690\0\u06c0"+
    "\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0270\0\u0810"+
    "\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930\0\u0960\0\u0990"+
    "\0\u0270\0\300\0\u05a0\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80"+
    "\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0270\0\u0bd0"+
    "\0\u0270\0\u0270\0\u0c00\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0"+
    "\0\u0d20\0\u0d50\0\u0d80\0\u0db0\0\u0270\0\u0270\0\u0de0\0\u0e10"+
    "\0\u0e40\0\u0270\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00\0\u0f30\0\u0f60"+
    "\0\u0f90\0\u0fc0\0\u0270\0\u0ff0\0\u1020\0\u1050\0\u0270\0\u0270"+
    "\0\u1080\0\u10b0\0\u0270\0\u0270\0\u10e0\0\u1110\0\u1140\0\u1170"+
    "\0\u11a0\0\u11d0\0\u0270\0\u0270\0\u1200\0\u1230\0\u0270\0\u0270"+
    "\0\u1260\0\u1290\0\u0270\0\u0270\0\u0270\0\u0270\0\u0270\0\u0270"+
    "\0\u12c0\0\u12f0\0\u0270";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\31"+
    "\1\34\1\35\1\36\1\37\1\40\2\31\1\41\3\31"+
    "\1\42\1\31\1\43\1\44\1\45\1\46\2\31\1\47"+
    "\1\50\1\51\1\52\4\53\1\54\53\53\2\55\1\56"+
    "\1\55\1\56\4\55\1\57\50\55\1\60\1\55\1\56"+
    "\53\55\103\0\1\61\41\0\1\62\52\0\60\63\11\0"+
    "\1\64\4\0\1\65\56\0\1\66\1\0\1\23\63\0"+
    "\1\67\57\0\1\70\57\0\1\71\53\0\1\31\5\0"+
    "\2\31\1\72\25\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\21\31\1\73\3\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\15\31\1\74\1\31\1\75"+
    "\5\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\1\76\6\31\1\77\2\31\1\100\12\31\1\0\1\31"+
    "\20\0\1\31\5\0\2\31\1\72\4\31\1\101\10\31"+
    "\1\102\7\31\1\0\1\31\20\0\1\31\5\0\2\31"+
    "\1\72\12\31\1\103\12\31\1\0\1\31\20\0\1\31"+
    "\5\0\2\31\1\72\1\104\7\31\1\105\4\31\1\106"+
    "\7\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\5\31\1\107\5\31\1\110\1\111\10\31\1\0\1\31"+
    "\20\0\1\31\5\0\2\31\1\72\4\31\1\112\20\31"+
    "\1\0\1\31\20\0\1\31\5\0\2\31\1\72\17\31"+
    "\1\113\2\31\1\114\2\31\1\0\1\31\20\0\1\31"+
    "\5\0\2\31\1\72\4\31\1\115\20\31\1\0\1\31"+
    "\20\0\1\31\5\0\2\31\1\72\24\31\1\116\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\17\31\1\117"+
    "\5\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\7\31\1\120\15\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\25\31\1\0\1\121\17\0\1\60\47\0"+
    "\1\122\70\0\1\123\57\0\1\31\5\0\2\31\1\72"+
    "\17\31\1\124\5\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\15\31\1\125\7\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\4\31\1\126\20\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\20\31\1\127"+
    "\4\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\1\130\24\31\1\0\1\31\20\0\1\31\5\0\2\31"+
    "\1\72\1\131\24\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\5\31\1\132\17\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\22\31\1\133\2\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\20\31\1\134"+
    "\4\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\12\31\1\135\12\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\14\31\1\136\10\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\17\31\1\137\5\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\16\31\1\140"+
    "\6\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\21\31\1\141\3\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\24\31\1\142\1\0\1\31\20\0\1\31"+
    "\5\0\2\31\1\72\10\31\1\143\4\31\1\144\7\31"+
    "\1\0\1\31\20\0\1\31\5\0\2\31\1\72\1\31"+
    "\1\145\23\31\1\0\1\31\20\0\1\31\5\0\2\31"+
    "\1\72\21\31\1\146\3\31\1\0\1\31\20\0\1\31"+
    "\5\0\2\31\1\72\10\31\1\147\14\31\1\0\1\31"+
    "\20\0\1\31\5\0\2\31\1\72\22\31\1\150\2\31"+
    "\1\0\1\31\20\0\1\31\5\0\2\31\1\72\10\31"+
    "\1\151\14\31\1\0\1\31\20\0\1\31\5\0\2\31"+
    "\1\72\10\31\1\152\14\31\1\0\1\31\20\0\1\31"+
    "\5\0\2\31\1\72\12\31\1\153\12\31\1\0\1\31"+
    "\20\0\1\31\5\0\2\31\1\72\1\154\24\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\4\31\1\155"+
    "\20\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\17\31\1\156\5\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\20\31\1\157\4\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\1\160\24\31\1\0\1\31"+
    "\20\0\1\31\5\0\2\31\1\72\1\31\1\161\23\31"+
    "\1\0\1\31\20\0\1\31\5\0\2\31\1\72\4\31"+
    "\1\162\20\31\1\0\1\31\20\0\1\31\5\0\2\31"+
    "\1\72\20\31\1\163\4\31\1\0\1\31\20\0\1\31"+
    "\5\0\2\31\1\72\1\164\24\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\15\31\1\165\7\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\23\31\1\166"+
    "\1\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\21\31\1\167\3\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\12\31\1\170\12\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\22\31\1\171\2\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\21\31\1\172"+
    "\3\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\4\31\1\173\20\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\12\31\1\174\12\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\14\31\1\175\10\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\4\31\1\176"+
    "\20\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\11\31\1\177\13\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\20\31\1\200\4\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\22\31\1\201\2\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\12\31\1\202"+
    "\12\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\4\31\1\203\20\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\12\31\1\204\12\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\17\31\1\205\5\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\1\206\24\31"+
    "\1\0\1\31\20\0\1\31\5\0\2\31\1\72\4\31"+
    "\1\207\20\31\1\0\1\31\20\0\1\31\5\0\2\31"+
    "\1\72\10\31\1\210\14\31\1\0\1\31\20\0\1\31"+
    "\5\0\2\31\1\72\17\31\1\211\5\31\1\0\1\31"+
    "\20\0\1\31\5\0\2\31\1\72\2\31\1\212\22\31"+
    "\1\0\1\31\20\0\1\31\5\0\2\31\1\72\4\31"+
    "\1\213\20\31\1\0\1\31\20\0\1\31\5\0\2\31"+
    "\1\72\6\31\1\214\16\31\1\0\1\31\20\0\1\31"+
    "\5\0\2\31\1\72\1\215\24\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\12\31\1\216\12\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\4\31\1\217"+
    "\20\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\21\31\1\220\3\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\21\31\1\221\3\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\2\31\1\222\22\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\2\31\1\223"+
    "\22\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\14\31\1\224\10\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\7\31\1\225\15\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\14\31\1\226\10\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\21\31\1\227"+
    "\3\31\1\0\1\31\20\0\1\31\5\0\2\31\1\72"+
    "\4\31\1\230\20\31\1\0\1\31\20\0\1\31\5\0"+
    "\2\31\1\72\21\31\1\231\3\31\1\0\1\31\20\0"+
    "\1\31\5\0\2\31\1\72\4\31\1\232\20\31\1\0"+
    "\1\31\20\0\1\31\5\0\2\31\1\72\3\31\1\233"+
    "\21\31\1\0\1\31\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4896];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\1\1\1\11\2\1\7\11\2\1\2\11"+
    "\22\1\1\11\1\1\5\11\1\1\3\11\1\0\2\11"+
    "\1\0\3\11\1\0\27\1\1\11\111\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  
    private Symbol symbol(int type, String lexema) {
        return new Symbol(type, new Token(lexema, yyline + 1, yycolumn + 1));
    }
    private TablaSimbolo tabla = new TablaSimbolo();
    private String cadena ="";
    private String comentario="";
    private ArrayList<errorE> errores = new ArrayList<>();
    private boolean isProyecto1 = true;



    public void setErrores(ArrayList errores) {
        this.errores = errores;
    }

    public ArrayList getErrores() {
        return errores;
    }


    public void setTabla(TablaSimbolo tabla){
        this.tabla = tabla;
    }
    public TablaSimbolo getTable(){
        return this.tabla;
    }
         public boolean isIsProyecto1() {
        return isProyecto1;
    }

    public void setIsProyecto1(boolean isProyecto1) {
        this.isProyecto1 = isProyecto1;
    }
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoJava(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    

  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.add(new errorE(yytext(),yyline + 1,yycolumn + 1,"No existe en el lenguaje","Lexico","---",isProyecto1));
            }
            // fall through
          case 61: break;
          case 2:
            { /* ignoramos */
            }
            // fall through
          case 62: break;
          case 3:
            { return symbol(sym.NEGATION,yytext());
            }
            // fall through
          case 63: break;
          case 4:
            { yybegin(CADE);
            }
            // fall through
          case 64: break;
          case 5:
            { return symbol(sym.PARENTESISA,yytext());
            }
            // fall through
          case 65: break;
          case 6:
            { return symbol(sym.PARENTESISC,yytext());
            }
            // fall through
          case 66: break;
          case 7:
            { return symbol(sym.MULTIPLICACION,yytext());
            }
            // fall through
          case 67: break;
          case 8:
            { return symbol(sym.MAS,yytext());
            }
            // fall through
          case 68: break;
          case 9:
            { return symbol(sym.COMA,yytext());
            }
            // fall through
          case 69: break;
          case 10:
            { return symbol(sym.MENOS,yytext());
            }
            // fall through
          case 70: break;
          case 11:
            { return symbol(sym.PUNTO,yytext());
            }
            // fall through
          case 71: break;
          case 12:
            { return symbol(sym.DIVISION,yytext());
            }
            // fall through
          case 72: break;
          case 13:
            { return symbol(sym.ENTERO,yytext());
            }
            // fall through
          case 73: break;
          case 14:
            { return symbol(sym.DOPUNTO,yytext());
            }
            // fall through
          case 74: break;
          case 15:
            { return symbol(sym.PUNTOCOMA,yytext());
            }
            // fall through
          case 75: break;
          case 16:
            { return symbol(sym.MENORQ,yytext());
            }
            // fall through
          case 76: break;
          case 17:
            { return symbol(sym.IGUAL,yytext());
            }
            // fall through
          case 77: break;
          case 18:
            { return symbol(sym.MAYORQ,yytext());
            }
            // fall through
          case 78: break;
          case 19:
            { return symbol(sym.ID,yytext());
            }
            // fall through
          case 79: break;
          case 20:
            { return symbol(sym.LLAVEA,yytext());
            }
            // fall through
          case 80: break;
          case 21:
            { return symbol(sym.LLAVEC,yytext());
            }
            // fall through
          case 81: break;
          case 22:
            { cadena+=yytext();
            }
            // fall through
          case 82: break;
          case 23:
            { yybegin(YYINITIAL); return symbol(sym.CADENA, cadena);
            }
            // fall through
          case 83: break;
          case 24:
            { comentario+=yytext();
            }
            // fall through
          case 84: break;
          case 25:
            { ;
            }
            // fall through
          case 85: break;
          case 26:
            { yybegin(YYINITIAL); this.tabla.getComentarios().add(comentario); comentario = "";
            }
            // fall through
          case 86: break;
          case 27:
            { return symbol(sym.NOTEQUALS,yytext());
            }
            // fall through
          case 87: break;
          case 28:
            { return symbol(sym.AND,yytext());
            }
            // fall through
          case 88: break;
          case 29:
            { yybegin(COMENTMULTILINEA);
            }
            // fall through
          case 89: break;
          case 30:
            { yybegin(COMENTLINEA);
            }
            // fall through
          case 90: break;
          case 31:
            { return symbol(sym.MENOROI,yytext());
            }
            // fall through
          case 91: break;
          case 32:
            { return symbol(sym.EQUALS,yytext());
            }
            // fall through
          case 92: break;
          case 33:
            { return symbol(sym.MAYOROI,yytext());
            }
            // fall through
          case 93: break;
          case 34:
            { return symbol(sym.DO,yytext());
            }
            // fall through
          case 94: break;
          case 35:
            { return symbol(sym.IF,yytext());
            }
            // fall through
          case 95: break;
          case 36:
            { return symbol(sym.OR,yytext());
            }
            // fall through
          case 96: break;
          case 37:
            { return symbol(sym.CARACTER,yytext());
            }
            // fall through
          case 97: break;
          case 38:
            { return symbol(sym.DECIMAL,yytext());
            }
            // fall through
          case 98: break;
          case 39:
            { return symbol(sym.FOR,yytext());
            }
            // fall through
          case 99: break;
          case 40:
            { return symbol(sym.INT,yytext());
            }
            // fall through
          case 100: break;
          case 41:
            { return symbol(sym.NEW,yytext());
            }
            // fall through
          case 101: break;
          case 42:
            { return symbol(sym.CASO,yytext());
            }
            // fall through
          case 102: break;
          case 43:
            { return symbol(sym.CHAR,yytext());
            }
            // fall through
          case 103: break;
          case 44:
            { return symbol(sym.ELSE,yytext());
            }
            // fall through
          case 104: break;
          case 45:
            { return symbol(sym.TRUE,yytext());
            }
            // fall through
          case 105: break;
          case 46:
            { return symbol(sym.BREAK,yytext());
            }
            // fall through
          case 106: break;
          case 47:
            { return symbol(sym.CLASS,yytext());
            }
            // fall through
          case 107: break;
          case 48:
            { return symbol(sym.FALSE,yytext());
            }
            // fall through
          case 108: break;
          case 49:
            { return symbol(sym.FINAL,yytext());
            }
            // fall through
          case 109: break;
          case 50:
            { return symbol(sym.WHILE,yytext());
            }
            // fall through
          case 110: break;
          case 51:
            { return symbol(sym.STRING,yytext());
            }
            // fall through
          case 111: break;
          case 52:
            { return symbol(sym.DOUBLE,yytext());
            }
            // fall through
          case 112: break;
          case 53:
            { return symbol(sym.IMPORT,yytext());
            }
            // fall through
          case 113: break;
          case 54:
            { return symbol(sym.PUBLIC,yytext());
            }
            // fall through
          case 114: break;
          case 55:
            { return symbol(sym.RETURN,yytext());
            }
            // fall through
          case 115: break;
          case 56:
            { return symbol(sym.SWITCH,yytext());
            }
            // fall through
          case 116: break;
          case 57:
            { return symbol(sym.BOOLEAN,yytext());
            }
            // fall through
          case 117: break;
          case 58:
            { return symbol(sym.DEFAULT,yytext());
            }
            // fall through
          case 118: break;
          case 59:
            { return symbol(sym.PRIVATE,yytext());
            }
            // fall through
          case 119: break;
          case 60:
            { return symbol(sym.PROTECTED,yytext());
            }
            // fall through
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
