package analisisHtml;

// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: /home/andaryus7/Escritorio/LexicoHTMLFIN.flex


import reporteHtml.Token;
import java.util.ArrayList;

import java_cup.runtime.*;




// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LexicoHtml implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int CADE = 2;
  public static final int COMENTARIO = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\22\0\1\1\1\0\1\2\1\0\1\3"+
    "\3\0\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\7\14\1\17\1\20\1\21"+
    "\1\22\1\23\2\0\32\24\1\25\1\0\1\26\1\0"+
    "\1\27\1\0\1\30\1\31\1\24\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\2\24\1\40\1\41\1\42\1\43"+
    "\2\24\1\44\1\45\1\46\6\24\1\0\1\47\10\0"+
    "\1\1\32\0\1\1\120\0\1\24\u018e\0\1\1\177\0"+
    "\13\1\35\0\2\1\5\0\1\1\57\0\1\1\240\0"+
    "\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\1\3\22"+
    "\1\2\1\25\1\26\2\27\1\30\1\0\1\31\5\22"+
    "\1\0\3\22\1\32\1\33\4\0\3\22\2\0\10\22"+
    "\10\0\1\34\1\35\1\36\1\37\2\22\1\40\1\41"+
    "\1\42\3\22\1\0\1\43\1\44\2\0\1\45\1\46"+
    "\1\47\2\22\1\50\2\22\1\51\2\0\1\52\2\22"+
    "\1\53\1\54\1\0\1\55\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\170\0\170\0\240\0\170"+
    "\0\170\0\170\0\170\0\170\0\170\0\170\0\170\0\310"+
    "\0\170\0\170\0\360\0\170\0\170\0\u0118\0\170\0\170"+
    "\0\u0118\0\u0140\0\u0168\0\u0190\0\u0118\0\170\0\170\0\170"+
    "\0\u01b8\0\170\0\u01e0\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8"+
    "\0\u02d0\0\u0118\0\u02f8\0\u0320\0\u0348\0\170\0\u01e0\0\u0370"+
    "\0\u0398\0\u03c0\0\u03e8\0\170\0\u0410\0\u0438\0\u0460\0\u0488"+
    "\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05c8"+
    "\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708"+
    "\0\170\0\u0230\0\170\0\170\0\u0730\0\u0758\0\170\0\170"+
    "\0\170\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\170\0\170\0\u0820"+
    "\0\u0848\0\170\0\170\0\170\0\u0870\0\u0898\0\u0118\0\u08c0"+
    "\0\u08e8\0\170\0\u0910\0\u0938\0\170\0\u0960\0\u0988\0\u0118"+
    "\0\170\0\u09b0\0\170\0\u0118\0\170";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\3\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\6\26\1\32"+
    "\1\33\5\26\1\34\1\26\1\35\2\36\1\37\45\36"+
    "\13\40\1\41\34\40\53\0\1\42\56\0\1\43\1\0"+
    "\3\20\44\0\1\44\10\0\1\45\3\0\1\45\1\46"+
    "\2\45\1\47\1\45\1\50\7\45\1\51\1\45\14\0"+
    "\3\26\5\0\1\26\2\0\1\52\20\26\14\0\3\26"+
    "\5\0\1\26\2\0\1\52\1\53\17\26\14\0\3\26"+
    "\5\0\1\26\2\0\1\52\12\26\1\54\5\26\14\0"+
    "\3\26\5\0\1\26\2\0\1\52\16\26\1\55\1\26"+
    "\23\0\1\56\40\0\3\57\55\0\1\60\3\0\4\60"+
    "\1\61\1\60\1\62\7\60\1\63\1\60\23\0\1\64"+
    "\1\45\3\0\20\45\23\0\1\64\1\45\3\0\14\45"+
    "\1\65\3\45\23\0\1\64\1\45\3\0\13\45\1\66"+
    "\4\45\15\0\1\67\1\70\4\0\1\64\1\45\3\0"+
    "\16\45\1\71\1\45\23\0\1\64\1\45\3\0\1\72"+
    "\1\45\1\73\3\45\1\74\5\45\1\75\3\45\14\0"+
    "\3\26\5\0\1\26\2\0\1\52\15\26\1\76\2\26"+
    "\14\0\3\26\5\0\1\26\2\0\1\52\16\26\1\77"+
    "\1\26\14\0\3\26\5\0\1\26\2\0\1\52\14\26"+
    "\1\100\3\26\23\0\1\64\1\60\3\0\20\60\23\0"+
    "\1\64\1\60\3\0\13\60\1\101\4\60\15\0\1\102"+
    "\1\103\4\0\1\64\1\60\3\0\16\60\1\104\1\60"+
    "\23\0\1\64\1\60\3\0\1\105\1\60\1\106\3\60"+
    "\1\107\5\60\1\110\3\60\23\0\1\111\1\45\3\0"+
    "\20\45\23\0\1\64\1\45\3\0\14\45\1\112\3\45"+
    "\23\0\1\113\47\0\1\114\47\0\1\64\1\45\3\0"+
    "\11\45\1\115\6\45\23\0\1\64\1\45\3\0\1\45"+
    "\1\116\16\45\23\0\1\117\1\45\3\0\20\45\23\0"+
    "\1\120\1\45\3\0\20\45\23\0\1\121\1\45\3\0"+
    "\20\45\14\0\3\26\5\0\1\26\2\0\1\52\16\26"+
    "\1\122\1\26\14\0\3\26\5\0\1\26\2\0\1\52"+
    "\3\26\1\123\14\26\14\0\3\26\5\0\1\26\2\0"+
    "\1\52\7\26\1\124\10\26\23\0\1\64\1\60\3\0"+
    "\14\60\1\125\3\60\23\0\1\126\47\0\1\127\47\0"+
    "\1\64\1\60\3\0\11\60\1\130\6\60\23\0\1\64"+
    "\1\60\3\0\1\60\1\131\16\60\23\0\1\132\1\60"+
    "\3\0\20\60\23\0\1\133\1\60\3\0\20\60\23\0"+
    "\1\134\1\60\3\0\20\60\23\0\1\64\1\45\3\0"+
    "\10\45\1\135\7\45\23\0\1\64\1\45\3\0\10\45"+
    "\1\136\7\45\14\0\3\26\5\0\1\26\2\0\1\52"+
    "\1\137\17\26\14\0\3\26\5\0\1\26\2\0\1\52"+
    "\5\26\1\140\12\26\14\0\3\26\5\0\1\26\2\0"+
    "\1\52\12\26\1\141\5\26\23\0\1\142\1\60\3\0"+
    "\20\60\23\0\1\64\1\60\3\0\10\60\1\143\7\60"+
    "\23\0\1\64\1\60\3\0\10\60\1\144\7\60\23\0"+
    "\1\145\1\45\3\0\20\45\23\0\1\64\1\45\3\0"+
    "\3\45\1\146\14\45\14\0\3\26\5\0\1\26\2\0"+
    "\1\52\3\26\1\147\14\26\14\0\3\26\5\0\1\26"+
    "\2\0\1\52\5\26\1\150\12\26\23\0\1\151\1\60"+
    "\3\0\20\60\23\0\1\64\1\60\3\0\3\60\1\152"+
    "\14\60\23\0\1\153\1\45\3\0\20\45\14\0\3\26"+
    "\5\0\1\26\2\0\1\52\14\26\1\154\3\26\23\0"+
    "\1\155\1\60\3\0\20\60";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2520];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\3\11\1\1\10\11\1\1\2\11\1\1\2\11"+
    "\1\1\2\11\5\1\3\11\1\1\1\11\1\0\6\1"+
    "\1\0\3\1\1\11\1\1\4\0\1\11\2\1\2\0"+
    "\10\1\10\0\1\11\1\1\2\11\2\1\3\11\3\1"+
    "\1\0\2\11\2\0\3\11\5\1\1\11\2\0\1\11"+
    "\3\1\1\11\1\0\1\11\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private String cadena ="";
    private String auxAnteriror = "";
    private boolean tomarEncuenta = true;

    private Symbol symbol(int type, String lexema) {
        return new Symbol(type, new Token(lexema, yyline + 1, yycolumn + 1));
    }
    private Symbol symbolReservado(String lexema) {
        String aux = lexema.toLowerCase();
        int type;
        switch(aux){
            case "<html>":
                type = sym.HTMLINICIO;
                break;
            case "</html>":
                type = sym.HTMLFIN;
                break;
            case "<h1>":
                type = sym.H1INICIO;
                break;    
            case "</h1>":
                type = sym.H1FIN;
                break;
            case "<h2>":
                type = sym.H2INICIO;
                break;
            case "</h2>":
                type = sym.H2FIN;
                break;
            case "<table>":
                type = sym.TABLAINICIO;
                break;
            case "</table>":
                type = sym.TABLAFIN;
                break;
            case "<tr>":
                type = sym.TRINICIO;
                break;
            case "</tr>":
                type = sym.TRFIN;
                break;
            case "<th>":
                type = sym.THINICIO;
                break;
            case "</th>":
                type = sym.THFIN;
                break;
            case "<td>":
                type = sym.TDINICIO;
                break;
            case "</td>":
                type = sym.TDFIN;
                break;
            case "<br>":
                type = sym.SALTO;
                break;
            case "<for":
                type = sym.FORINICIO;
                break;
            case "</for>":
                type = sym.FORFIN;
                break;
            case "integer":
                type = sym.INTEGER;
                break;
            case "string":
                type = sym.STRING;
                break;
            case "hasta":
                type = sym.HASTA;
                break;
            case "iterador":
                type = sym.ITERADOR;
                break;
            case "result":
                type = sym.RESULT;
                break; 
            case "score":
                type = sym.SCORE;
                break;   
            case "variables":
                if(auxAnteriror.equals("result")){
                    type = sym.VARIABLES;
                }else{
                    type = sym.IDD;
                }
                break;
            case "clases":
                if(auxAnteriror.equals("result")){
                    type = sym.CLASES;
                }else{
                    type = sym.IDD;
                }
                break;
            case "nombre":
                if(auxAnteriror.equals("variables") || auxAnteriror.equals("metodos") || auxAnteriror.equals("clases")){
                    type = sym.NOMBRE;
                }else{
                    type = sym.IDD;
                }
                break;
            case "tipo":
                if(auxAnteriror.equals("variables") || auxAnteriror.equals("metodos")){
                    type = sym.TIPO;
                }else{
                    type = sym.IDD;
                }
                break;
            case "funcion":
                if(auxAnteriror.equals("variables")){
                    type = sym.FUNCION;
                }else{
                    type = sym.IDD;
                }
                break;
            case "metodos":
                if(auxAnteriror.equals("result")){
                    type = sym.METODOS;
                }else{
                    type = sym.IDD;
                }
                break;
            case "comentarios":
                if(auxAnteriror.equals("result")){
                    type = sym.COMENTARIOS;
                }else{
                    type = sym.IDD;
                }
                break;
            case "texto":
                if(auxAnteriror.equals("comentarios")){
                    type = sym.TEXTO;
                }else{
                    type = sym.IDD;
                }
                break;
            case "parametros":
                if(auxAnteriror.equals("metodos")){
                    type = sym.PARAMTETROS;
                }else{
                    type = sym.IDD;
                }
                break;
            default:
                type = sym.IDD;
                break;
        }
        if(tomarEncuenta){
            auxAnteriror = aux;
        }
        return new Symbol(type, new Token(lexema, yyline + 1, yycolumn + 1));
    }
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoHtml(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    

  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error simbolo: "+yytext());
            }
            // fall through
          case 48: break;
          case 2:
            { /* ignoramos */
            }
            // fall through
          case 49: break;
          case 3:
            { cadena =""; yybegin(CADE);
            }
            // fall through
          case 50: break;
          case 4:
            { return symbol(sym.PARENTESISA,yytext());
            }
            // fall through
          case 51: break;
          case 5:
            { return symbol(sym.PARENTESISC,yytext());
            }
            // fall through
          case 52: break;
          case 6:
            { return symbol(sym.POR,yytext());
            }
            // fall through
          case 53: break;
          case 7:
            { return symbol(sym.MAS,yytext());
            }
            // fall through
          case 54: break;
          case 8:
            { return symbol(sym.COMA,yytext());
            }
            // fall through
          case 55: break;
          case 9:
            { return symbol(sym.MENOS,yytext());
            }
            // fall through
          case 56: break;
          case 10:
            { return symbol(sym.PUNTO,yytext());
            }
            // fall through
          case 57: break;
          case 11:
            { return symbol(sym.DIVISION,yytext());
            }
            // fall through
          case 58: break;
          case 12:
            { return symbol(sym.ENTERO,yytext());
            }
            // fall through
          case 59: break;
          case 13:
            { return symbol(sym.DOSPUNTO,yytext());
            }
            // fall through
          case 60: break;
          case 14:
            { return symbol(sym.PUNTOCOMA,yytext());
            }
            // fall through
          case 61: break;
          case 15:
            { return symbol(sym.MENOR,yytext());
            }
            // fall through
          case 62: break;
          case 16:
            { return symbol(sym.IGUAL,yytext());
            }
            // fall through
          case 63: break;
          case 17:
            { return symbol(sym.MAYOR,yytext());
            }
            // fall through
          case 64: break;
          case 18:
            { return symbolReservado(yytext());
            }
            // fall through
          case 65: break;
          case 19:
            { tomarEncuenta = false; return symbol(sym.CORCHETEA,yytext());
            }
            // fall through
          case 66: break;
          case 20:
            { tomarEncuenta = true;  return symbol(sym.CORCHETEC,yytext());
            }
            // fall through
          case 67: break;
          case 21:
            { cadena+=yytext();
            }
            // fall through
          case 68: break;
          case 22:
            { yybegin(YYINITIAL); return symbol(sym.CADENA, cadena);
            }
            // fall through
          case 69: break;
          case 23:
            { ;
            }
            // fall through
          case 70: break;
          case 24:
            { return symbol(sym.COMODIN,yytext());
            }
            // fall through
          case 71: break;
          case 25:
            { yybegin(COMENTARIO);
            }
            // fall through
          case 72: break;
          case 26:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 73: break;
          case 27:
            { return symbol(sym.DECIMAL,yytext());
            }
            // fall through
          case 74: break;
          case 28:
            { return symbol(sym.SALTO,yytext());
            }
            // fall through
          case 75: break;
          case 29:
            { return symbol(sym.FORINICIO,yytext());
            }
            // fall through
          case 76: break;
          case 30:
            { return symbol(sym.H1INICIO,yytext());
            }
            // fall through
          case 77: break;
          case 31:
            { return symbol(sym.H2INICIO,yytext());
            }
            // fall through
          case 78: break;
          case 32:
            { return symbol(sym.TDINICIO,yytext());
            }
            // fall through
          case 79: break;
          case 33:
            { return symbol(sym.THINICIO,yytext());
            }
            // fall through
          case 80: break;
          case 34:
            { return symbol(sym.TRINICIO,yytext());
            }
            // fall through
          case 81: break;
          case 35:
            { return symbol(sym.H1FIN,yytext());
            }
            // fall through
          case 82: break;
          case 36:
            { return symbol(sym.H2FIN,yytext());
            }
            // fall through
          case 83: break;
          case 37:
            { return symbol(sym.TDFIN,yytext());
            }
            // fall through
          case 84: break;
          case 38:
            { return symbol(sym.THFIN,yytext());
            }
            // fall through
          case 85: break;
          case 39:
            { return symbol(sym.TRFIN,yytext());
            }
            // fall through
          case 86: break;
          case 40:
            { return symbol(sym.HASTA,yytext());
            }
            // fall through
          case 87: break;
          case 41:
            { return symbol(sym.FORFIN,yytext());
            }
            // fall through
          case 88: break;
          case 42:
            { return symbol(sym.HTMLINICIO,yytext());
            }
            // fall through
          case 89: break;
          case 43:
            { return symbol(sym.STRING,yytext());
            }
            // fall through
          case 90: break;
          case 44:
            { return symbol(sym.HTMLFIN,yytext());
            }
            // fall through
          case 91: break;
          case 45:
            { return symbol(sym.TABLAINICIO,yytext());
            }
            // fall through
          case 92: break;
          case 46:
            { return symbol(sym.INTEGER,yytext());
            }
            // fall through
          case 93: break;
          case 47:
            { return symbol(sym.TABLAFIN,yytext());
            }
            // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
