
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisisJson;


import reporteHtml.Token;

import java_cup.runtime.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;
import objetosAnalisis.errorE;
import tablaSimbolo.TablaSimbolo;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class JsonSintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public JsonSintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public JsonSintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public JsonSintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\102\000\002\002\004\000\002\002\005\000\002\021" +
    "\007\000\002\006\010\000\002\006\010\000\002\006\004" +
    "\000\002\003\010\000\002\003\007\000\002\003\004\000" +
    "\002\004\007\000\002\004\005\000\002\004\004\000\002" +
    "\005\007\000\002\005\004\000\002\007\010\000\002\007" +
    "\007\000\002\007\004\000\002\011\007\000\002\011\005" +
    "\000\002\011\004\000\002\010\007\000\002\010\004\000" +
    "\002\012\007\000\002\012\004\000\002\013\007\000\002" +
    "\013\004\000\002\014\007\000\002\014\004\000\002\020" +
    "\004\000\002\022\007\000\002\022\005\000\002\022\006" +
    "\000\002\022\006\000\002\022\004\000\002\023\004\000" +
    "\002\023\002\000\002\023\004\000\002\034\005\000\002" +
    "\034\004\000\002\024\010\000\002\024\007\000\002\024" +
    "\004\000\002\025\007\000\002\025\005\000\002\025\004" +
    "\000\002\017\007\000\002\017\004\000\002\027\007\000" +
    "\002\027\004\000\002\030\007\000\002\030\004\000\002" +
    "\026\005\000\002\026\004\000\002\015\007\000\002\015" +
    "\006\000\002\015\004\000\002\033\007\000\002\033\005" +
    "\000\002\032\007\000\002\032\004\000\002\031\004\000" +
    "\002\031\003\000\002\016\003\000\002\016\003\000\002" +
    "\016\003\000\002\016\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\262\000\004\027\004\001\002\000\006\003\010\004" +
    "\011\001\002\000\004\002\006\001\002\000\004\002\001" +
    "\001\002\000\004\030\264\001\002\000\006\003\014\005" +
    "\015\001\002\000\004\020\253\001\002\000\006\003\014" +
    "\005\015\001\002\000\006\003\043\006\044\001\002\000" +
    "\006\003\043\006\044\001\002\000\004\020\016\001\002" +
    "\000\004\025\017\001\002\000\010\003\020\026\022\027" +
    "\021\001\002\000\004\030\042\001\002\000\006\003\027" +
    "\013\030\001\002\000\004\021\026\001\002\000\004\026" +
    "\024\001\002\000\004\021\025\001\002\000\010\003\ufffb" +
    "\005\ufffb\006\ufffb\001\002\000\010\003\ufffa\005\ufffa\006" +
    "\ufffa\001\002\000\004\030\041\001\002\000\004\020\035" +
    "\001\002\000\004\030\032\001\002\000\006\021\033\026" +
    "\ufff7\001\002\000\006\003\020\027\021\001\002\000\004" +
    "\026\ufff8\001\002\000\004\024\036\001\002\000\004\016" +
    "\037\001\002\000\004\024\040\001\002\000\004\030\ufff5" +
    "\001\002\000\004\030\ufff4\001\002\000\004\026\ufff6\001" +
    "\002\000\006\003\142\007\144\001\002\000\004\020\046" +
    "\001\002\000\010\003\ufff9\005\ufff9\006\ufff9\001\002\000" +
    "\004\025\047\001\002\000\010\003\051\026\052\027\050" +
    "\001\002\000\006\003\061\013\062\001\002\000\004\030" +
    "\057\001\002\000\004\021\056\001\002\000\004\026\054" +
    "\001\002\000\004\021\055\001\002\000\012\003\ufff3\005" +
    "\ufff3\006\ufff3\007\ufff3\001\002\000\012\003\ufff2\005\ufff2" +
    "\006\ufff2\007\ufff2\001\002\000\004\026\uffee\001\002\000" +
    "\004\030\137\001\002\000\006\021\135\030\136\001\002" +
    "\000\004\020\131\001\002\000\004\021\064\001\002\000" +
    "\006\003\065\012\067\001\002\000\004\021\130\001\002" +
    "\000\004\021\074\001\002\000\004\020\070\001\002\000" +
    "\004\024\071\001\002\000\004\016\072\001\002\000\004" +
    "\024\073\001\002\000\004\021\uffe9\001\002\000\006\003" +
    "\075\011\076\001\002\000\004\030\127\001\002\000\004" +
    "\020\100\001\002\000\004\030\uffed\001\002\000\004\024" +
    "\101\001\002\000\006\003\103\016\105\001\002\000\004" +
    "\024\126\001\002\000\004\024\125\001\002\000\010\003" +
    "\117\021\115\024\uffde\001\002\000\006\016\107\021\106" +
    "\001\002\000\004\016\113\001\002\000\004\021\110\001" +
    "\002\000\004\016\111\001\002\000\012\003\uffe1\016\112" +
    "\021\uffe1\024\uffe1\001\002\000\010\003\uffe4\021\uffe4\024" +
    "\uffe4\001\002\000\012\003\uffe3\016\114\021\uffe3\024\uffe3" +
    "\001\002\000\010\003\uffe2\021\uffe2\024\uffe2\001\002\000" +
    "\004\016\123\001\002\000\004\024\uffe5\001\002\000\004" +
    "\024\122\001\002\000\010\003\117\021\115\024\uffde\001" +
    "\002\000\004\024\uffdf\001\002\000\004\024\uffdd\001\002" +
    "\000\012\003\uffdb\016\124\021\uffdb\024\uffdb\001\002\000" +
    "\010\003\uffdc\021\uffdc\024\uffdc\001\002\000\010\003\uffe0" +
    "\021\uffe0\024\uffe0\001\002\000\004\030\uffe7\001\002\000" +
    "\004\030\uffe6\001\002\000\004\021\uffe8\001\002\000\004" +
    "\024\132\001\002\000\004\016\133\001\002\000\004\024" +
    "\134\001\002\000\004\021\uffeb\001\002\000\004\021\uffea" +
    "\001\002\000\004\030\uffec\001\002\000\006\021\140\026" +
    "\uffef\001\002\000\006\003\051\027\050\001\002\000\004" +
    "\026\ufff0\001\002\000\006\003\214\010\216\001\002\000" +
    "\012\003\ufff1\005\ufff1\006\ufff1\007\ufff1\001\002\000\004" +
    "\020\145\001\002\000\004\025\146\001\002\000\010\003" +
    "\150\026\152\027\151\001\002\000\004\026\212\001\002" +
    "\000\004\030\211\001\002\000\006\003\155\013\157\001" +
    "\002\000\004\021\153\001\002\000\014\003\uffd9\005\uffd9" +
    "\006\uffd9\007\uffd9\010\uffd9\001\002\000\004\021\171\001" +
    "\002\000\006\021\167\030\170\001\002\000\004\030\164" +
    "\001\002\000\004\020\160\001\002\000\004\024\161\001" +
    "\002\000\004\016\162\001\002\000\004\024\163\001\002" +
    "\000\004\021\uffd2\001\002\000\006\021\165\026\uffd6\001" +
    "\002\000\006\003\150\027\151\001\002\000\004\026\uffd7" +
    "\001\002\000\004\021\uffd1\001\002\000\004\030\uffd3\001" +
    "\002\000\006\003\172\012\174\001\002\000\004\021\210" +
    "\001\002\000\004\021\201\001\002\000\004\020\175\001" +
    "\002\000\004\024\176\001\002\000\004\016\177\001\002" +
    "\000\004\024\200\001\002\000\004\021\uffd0\001\002\000" +
    "\006\003\203\014\204\001\002\000\004\030\uffd4\001\002" +
    "\000\004\030\207\001\002\000\004\020\205\001\002\000" +
    "\004\022\206\001\002\000\004\030\uffce\001\002\000\004" +
    "\030\uffcd\001\002\000\004\021\uffcf\001\002\000\004\026" +
    "\uffd5\001\002\000\004\021\213\001\002\000\014\003\uffda" +
    "\005\uffda\006\uffda\007\uffda\010\uffda\001\002\000\004\030" +
    "\247\001\002\000\014\003\uffd8\005\uffd8\006\uffd8\007\uffd8" +
    "\010\uffd8\001\002\000\004\020\217\001\002\000\004\025" +
    "\220\001\002\000\006\026\223\027\222\001\002\000\004" +
    "\026\246\001\002\000\006\003\225\015\224\001\002\000" +
    "\016\003\uffcb\005\uffcb\006\uffcb\007\uffcb\010\uffcb\030\uffcb" +
    "\001\002\000\004\020\233\001\002\000\004\030\232\001" +
    "\002\000\004\030\227\001\002\000\006\021\230\026\uffc8" +
    "\001\002\000\004\027\222\001\002\000\004\026\uffc9\001" +
    "\002\000\004\030\uffc6\001\002\000\004\024\234\001\002" +
    "\000\012\003\237\016\242\017\241\021\235\001\002\000" +
    "\014\003\uffc1\016\uffc1\017\uffc1\021\uffc1\024\uffc1\001\002" +
    "\000\004\024\245\001\002\000\004\024\244\001\002\000" +
    "\014\003\237\016\242\017\241\021\235\024\uffc4\001\002" +
    "\000\014\003\uffc2\016\uffc2\017\uffc2\021\uffc2\024\uffc2\001" +
    "\002\000\014\003\uffc3\016\uffc3\017\uffc3\021\uffc3\024\uffc3" +
    "\001\002\000\004\024\uffc5\001\002\000\014\003\uffc0\016" +
    "\uffc0\017\uffc0\021\uffc0\024\uffc0\001\002\000\004\030\uffc7" +
    "\001\002\000\016\003\uffcc\005\uffcc\006\uffcc\007\uffcc\010" +
    "\uffcc\030\uffcc\001\002\000\016\003\uffca\005\uffca\006\uffca" +
    "\007\uffca\010\uffca\030\uffca\001\002\000\006\003\142\007" +
    "\144\001\002\000\006\003\214\010\216\001\002\000\004" +
    "\030\uffff\001\002\000\004\024\254\001\002\000\006\022" +
    "\256\023\255\001\002\000\004\024\261\001\002\000\004" +
    "\024\257\001\002\000\004\021\260\001\002\000\006\003" +
    "\ufffe\005\ufffe\001\002\000\004\021\262\001\002\000\006" +
    "\003\ufffd\005\ufffd\001\002\000\006\003\ufffc\005\ufffc\001" +
    "\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\262\000\004\002\004\001\001\000\006\006\011\021" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\262\001\001\000\002\001\001\000" +
    "\004\003\012\001\001\000\004\007\247\001\001\000\004" +
    "\007\044\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\022\001\001\000\002\001\001\000\004\005\030" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\033\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\024\142\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\052\001\001\000\006\010\057\012\062\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\065\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\076\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\020\101" +
    "\022\103\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\023\115\034\117\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\023\120\034\117\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\140\001\001\000\002\001\001\000" +
    "\004\015\214\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\025\146\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\017\155\027\153\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\025\165\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\030" +
    "\172\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\026\201\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\033\220\001\001\000\002\001\001\000" +
    "\004\032\225\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\033\230\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\016\237\031\235\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\016\237\031\242\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\024\250\001" +
    "\001\000\004\015\251\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$JsonSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$JsonSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$JsonSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


   
/*declaracion de variables para capturar Strigns para la tabla de simbolos*/

 /* Connect this parser to a scanner!*/
        private TablaSimbolo tabla = new TablaSimbolo();
        private String nombreVariable = "";
        private String tipoVariable = "";
        private String funcionPadre="";
        private String nombreMetodo ="";
        private String tipoMetodo="";
        private String parametros="";
        private String segComenario= "";
        private ArrayList<errorE> errores = new ArrayList<>();

	public JsonSintactico(LexicoJson analizadorLexico) {
		super(analizadorLexico);
	}

        @Override
        public void syntax_error(Symbol tok) {
	    try{
	        Token token = (Token) tok.value;
	        report_error("Error Sintactico con el  Token:"+ token.getLexema()+" este no pertenece a la estructura - linea: "+token.getFila()+" - columna: "+token.getColumna() + "\n",null);
                errores.add(new errorE(token.getLexema(),token.getFila(),token.getColumna(),"Se esperaba","Sintactico"));
            }catch(Exception e){
                e.printStackTrace();
	    }	
	}


    public void unrecovered_syntax_error(Symbol cur_token) {
        if (cur_token.sym == sym.EOF) {

           

        }else{
       
        }
    }

      public ArrayList<errorE> getErrores() {
        return errores;
    }

    public void setErrores(ArrayList<errorE> errores) {
        this.errores = errores;
    } 
     
     public TablaSimbolo getTabla() {
        return tabla;
    }

    public void setTabla(TablaSimbolo tabla) {
        this.tabla = tabla;
    }
   


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$JsonSintactico$actions {
  private final JsonSintactico parser;

  /** Constructor */
  CUP$JsonSintactico$actions(JsonSintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$JsonSintactico$do_action_part00000000(
    int                        CUP$JsonSintactico$act_num,
    java_cup.runtime.lr_parser CUP$JsonSintactico$parser,
    java.util.Stack            CUP$JsonSintactico$stack,
    int                        CUP$JsonSintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$JsonSintactico$result;

      /* select the action based on the action number */
      switch (CUP$JsonSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		RESULT = start_val;
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$JsonSintactico$parser.done_parsing();
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= LLAVEA componentes LLAVEC 
            {
              Object RESULT =null;
	
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // componentes ::= def_score def_clase def_variable def_metodo def_coment 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("componentes",15, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // def_score ::= SCORE DOSPUNTO COMILLAS ENTERO COMILLAS COMA 
            {
              Object RESULT =null;
		int scoreleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).left;
		int scoreright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).right;
		Token score = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).value;
		tabla.capturaScore(score.getLexema());
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_score",4, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // def_score ::= SCORE DOSPUNTO COMILLAS DECIMAL COMILLAS COMA 
            {
              Object RESULT =null;
		int scoreleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).left;
		int scoreright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).right;
		Token score = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).value;
		tabla.capturaScore(score.getLexema());
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_score",4, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // def_score ::= error def_clase 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_score",4, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // def_clase ::= CLASES DOSPUNTO CORCHETEA clases CORCHETEC COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_clase",1, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // def_clase ::= CLASES DOSPUNTO CORCHETEA CORCHETEC COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_clase",1, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // def_clase ::= error def_variable 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_clase",1, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // clases ::= LLAVEA clase LLAVEC COMA clases 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("clases",2, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // clases ::= LLAVEA clase LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("clases",2, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // clases ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("clases",2, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // clase ::= NOMBRE DOSPUNTO COMILLAS IDD COMILLAS 
            {
              Object RESULT =null;
		int nomClaseleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int nomClaseright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Token nomClase = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		tabla.capturarClase(nomClase.getLexema());
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("clase",3, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // clase ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("clase",3, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // def_variable ::= VARIBALES DOSPUNTO CORCHETEA variables CORCHETEC COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_variable",5, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // def_variable ::= VARIBALES DOSPUNTO CORCHETEA CORCHETEC COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_variable",5, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // def_variable ::= error def_metodo 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_variable",5, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // variables ::= LLAVEA variable LLAVEC COMA variables 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("variables",7, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // variables ::= LLAVEA variable LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("variables",7, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // variables ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("variables",7, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // variable ::= nom_Var COMA tipo_Var COMA funtions 
            {
              Object RESULT =null;
		tabla.capturaVar(nombreVariable, tipoVariable,funcionPadre);
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("variable",6, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // variable ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("variable",6, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // nom_Var ::= NOMBRE DOSPUNTO COMILLAS IDD COMILLAS 
            {
              Object RESULT =null;
		int nomVarleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int nomVarright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Token nomVar = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		nombreVariable = nomVar.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("nom_Var",8, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // nom_Var ::= error COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("nom_Var",8, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo_Var ::= TIPO DOSPUNTO COMILLAS IDD COMILLAS 
            {
              Object RESULT =null;
		int tipoVArleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int tipoVArright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Token tipoVAr = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		tipoVariable = tipoVAr.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("tipo_Var",9, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_Var ::= error COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("tipo_Var",9, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // funtions ::= FUNCION DOSPUNTO COMILLAS funcion_padre COMILLAS 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("funtions",10, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // funtions ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("funtions",10, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // funcion_padre ::= fun_oblig fun_Items 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("funcion_padre",14, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // fun_oblig ::= IDD IDD COMA IDD IDD 
            {
              Object RESULT =null;
		int tipo1left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)).left;
		int tipo1right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)).right;
		Token tipo1 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)).value;
		int funPadre1left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).left;
		int funPadre1right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).right;
		Token funPadre1 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).value;
		int tipo2left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int tipo2right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Token tipo2 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		int funPadre2left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int funPadre2right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token funPadre2 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		funcionPadre =tipo1.getLexema()+" "+funPadre1.getLexema()+ ","+ tipo2.getLexema()+" "+ funPadre2.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("fun_oblig",16, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // fun_oblig ::= IDD COMA IDD 
            {
              Object RESULT =null;
		int funleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).left;
		int funright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).right;
		Token fun = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).value;
		int funcionPleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int funcionPright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token funcionP = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		funcionPadre =fun.getLexema() +","+ funcionP.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("fun_oblig",16, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // fun_oblig ::= IDD COMA IDD IDD 
            {
              Object RESULT =null;
		int funPadre1left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).left;
		int funPadre1right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).right;
		Token funPadre1 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).value;
		int tipo2left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int tipo2right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Token tipo2 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		int funPadre2left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int funPadre2right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token funPadre2 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		funcionPadre = funPadre1.getLexema()+ ","+tipo2.getLexema()+" "+ funPadre2.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("fun_oblig",16, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // fun_oblig ::= IDD IDD COMA IDD 
            {
              Object RESULT =null;
		int tipo1left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).left;
		int tipo1right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).right;
		Token tipo1 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)).value;
		int funcionPleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).left;
		int funcionPright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).right;
		Token funcionP = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)).value;
		int funleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int funright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token fun = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		funcionPadre =tipo1.getLexema()+" "+funcionP.getLexema()+","+fun.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("fun_oblig",16, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // fun_oblig ::= error COMILLAS 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("fun_oblig",16, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // fun_Items ::= comodinItem fun_Items 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("fun_Items",17, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // fun_Items ::= 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("fun_Items",17, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // fun_Items ::= error COMILLAS 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("fun_Items",17, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // comodinItem ::= COMA IDD IDD 
            {
              Object RESULT =null;
		int tipo1left = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int tipo1right = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Token tipo1 = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		int funcionPleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int funcionPright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token funcionP = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		funcionPadre+= ","+tipo1.getLexema()+" "+funcionP.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("comodinItem",26, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // comodinItem ::= COMA IDD 
            {
              Object RESULT =null;
		int funcionPleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int funcionPright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token funcionP = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		funcionPadre+= ","+ funcionP.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("comodinItem",26, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // def_metodo ::= METODOS DOSPUNTO CORCHETEA metods CORCHETEC COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_metodo",18, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // def_metodo ::= METODOS DOSPUNTO CORCHETEA CORCHETEC COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_metodo",18, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // def_metodo ::= error def_coment 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_metodo",18, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // metods ::= LLAVEA metodo LLAVEC COMA metods 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("metods",19, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // metods ::= LLAVEA metodo LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("metods",19, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // metods ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("metods",19, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // metodo ::= nom_Metod COMA tipo_Metod COMA parametros 
            {
              Object RESULT =null;
		tabla.capturarMetodo(nombreMetodo, tipoMetodo, parametros);
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("metodo",13, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // metodo ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("metodo",13, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // nom_Metod ::= NOMBRE DOSPUNTO COMILLAS IDD COMILLAS 
            {
              Object RESULT =null;
		int nomMetodoleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int nomMetodoright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Token nomMetodo = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		nombreMetodo=nomMetodo.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("nom_Metod",21, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // nom_Metod ::= error COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("nom_Metod",21, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // tipo_Metod ::= TIPO DOSPUNTO COMILLAS IDD COMILLAS 
            {
              Object RESULT =null;
		int tipoMetodleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).left;
		int tipoMetodright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).right;
		Token tipoMetod = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)).value;
		tipoMetodo = tipoMetod.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("tipo_Metod",22, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // tipo_Metod ::= error COMA 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("tipo_Metod",22, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // parametros ::= PARAMTETROS DOSPUNTO ENTERO 
            {
              Object RESULT =null;
		int paramleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int paramright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token param = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		parametros=param.getLexema();
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("parametros",20, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // parametros ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("parametros",20, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // def_coment ::= COMENTARIOS DOSPUNTO CORCHETEA coments CORCHETEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_coment",11, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // def_coment ::= COMENTARIOS DOSPUNTO CORCHETEA CORCHETEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_coment",11, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // def_coment ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("def_coment",11, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // coments ::= LLAVEA text LLAVEC COMA coments 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("coments",25, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // coments ::= LLAVEA text LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("coments",25, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // text ::= TEXTO DOSPUNTO COMILLAS idd_Coment COMILLAS 
            {
              Object RESULT =null;
		tabla.capturarComentario(segComenario); segComenario="";
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("text",24, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // text ::= error LLAVEC 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("text",24, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // idd_Coment ::= comodinComent idd_Coment 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("idd_Coment",23, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // idd_Coment ::= comodinComent 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("idd_Coment",23, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // comodinComent ::= IDD 
            {
              Object RESULT =null;
		int comentarioleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int comentarioright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token comentario = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		segComenario+=" " +comentario.getLexema()+" ";
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("comodinComent",12, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // comodinComent ::= ALGO 
            {
              Object RESULT =null;
		int comentarioleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int comentarioright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token comentario = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		segComenario+=" "+ comentario.getLexema()+" ";
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("comodinComent",12, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // comodinComent ::= COMA 
            {
              Object RESULT =null;
		int comentarioleft = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).left;
		int comentarioright = ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()).right;
		Token comentario = (Token)((java_cup.runtime.Symbol) CUP$JsonSintactico$stack.peek()).value;
		segComenario+=" "+ comentario.getLexema()+" ";
              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("comodinComent",12, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // comodinComent ::= error COMILLAS 
            {
              Object RESULT =null;

              CUP$JsonSintactico$result = parser.getSymbolFactory().newSymbol("comodinComent",12, ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.elementAt(CUP$JsonSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$JsonSintactico$stack.peek()), RESULT);
            }
          return CUP$JsonSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$JsonSintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$JsonSintactico$do_action(
    int                        CUP$JsonSintactico$act_num,
    java_cup.runtime.lr_parser CUP$JsonSintactico$parser,
    java.util.Stack            CUP$JsonSintactico$stack,
    int                        CUP$JsonSintactico$top)
    throws java.lang.Exception
    {
              return CUP$JsonSintactico$do_action_part00000000(
                               CUP$JsonSintactico$act_num,
                               CUP$JsonSintactico$parser,
                               CUP$JsonSintactico$stack,
                               CUP$JsonSintactico$top);
    }
}

}
